# Generated by Django 5.2.6 on 2026-07-21 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Director', 'verbose_name_plural': 'Directores'},
        ),
    ]
