# Generated by Django 5.2.6 on 2026-07-25 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_distrito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Cluster',
                'verbose_name_plural': 'Clusters',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('nombre_corto', models.CharField(max_length=100, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.distrito')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=125)),
                ('apellidos', models.CharField(max_length=125)),
                ('telefono', models.CharField(max_length=9)),
                ('estado', models.BooleanField(default=True)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizacion.escuela')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directores',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=8)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.AddField(
            model_name='escuela',
            name='monitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizacion.monitor'),
        ),
    ]
