# Generated by Django 5.2.6 on 2026-07-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='zona',
            field=models.CharField(choices=[('S', 'SUR'), ('N', 'NORTE')], default='S', max_length=2),
        ),
    ]
