# Generated by Django 5.2.6 on 2026-07-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('organizacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.TextField()),
                ('fecha', models.DateField()),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='organizacion.escuela')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hallazgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='catalogo.catalogohallazgo')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='actividad.informe')),
            ],
        ),
        migrations.CreateModel(
            name='Fortaleza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fortaleza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortalezas', to='catalogo.catalogofortaleza')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortalezas', to='actividad.informe')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='catalogo.catalogoagenda')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='actividad.informe')),
            ],
        ),
        migrations.CreateModel(
            name='Acuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('responsable', models.CharField(max_length=250)),
                ('fecha', models.DateField()),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='actividad.informe')),
            ],
        ),
        migrations.CreateModel(
            name='Limitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limitaciones', to='actividad.informe')),
                ('limitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limitaciones', to='catalogo.catalogolimitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='actividad.informe')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='catalogo.catalogoobjetivos')),
            ],
        ),
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otros', to='actividad.informe')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadHombre', models.PositiveIntegerField(default=0)),
                ('cantidadMujer', models.PositiveIntegerField(default=0)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='actividad.informe')),
                ('tipoParticipante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='catalogo.catalogoparticipante')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='actividad.informe')),
                ('recomendacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='catalogo.catalogorecomendacion')),
            ],
        ),
    ]
