# Generated by Django 5.2.6 on 2026-07-28 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallazgo',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
