# Generated by Django 5.2.6 on 2026-07-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_hallazgo_descripcion'),
        ('catalogo', '0002_catalogoactividad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informe',
            name='actividad',
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='catalogo.catalogoactividad')),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='actividad.informe')),
            ],
        ),
    ]
